---
- name: Install system packages
  apt:
    name:
      - apache2-utils
      - nginx
      - python3-openssl
      - python3-passlib
      - ssl-cert
    state: latest
    update_cache: yes
  become: true
