---
- name: Create certificate and key directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ letsencryptnginx_crt_directory }}"
    - "{{ letsencryptnginx_csr_directory }}"
    - "{{ letsencryptnginx_private_key_path|dirname }}"
  become: true

- name: Create keys
  openssl_privatekey:
    path: "{{ item }}"
  loop:
    - "{{ letsencryptnginx_account_key_path }}"
    - "{{ letsencryptnginx_private_key_path }}"
  register: create_keys
  become: true

- name: Delete CSRs if keys have changed
  file:
    path: "{{ letsencryptnginx_csr_directory }}"
    state: absent
  when: create_keys is changed
  become: true

- name: Create CSR directory if keys have changed
  file:
    path: "{{ letsencryptnginx_csr_directory }}"
    state: directory
  when: create_keys is changed
  become: true

- name: Create CSRs
  openssl_csr:
    path: "{{ letsencryptnginx_csr_directory }}/{{ item.csr_common_name|default(item.domain)|replace('*', '_') }}.csr"
    privatekey_path: "{{ letsencryptnginx_private_key_path }}"
    countryName: "{{ letsencryptnginx_csr_country }}"
    commonName: "{{ item.csr_common_name|default(item.domain) }}"
  loop: "{{ letsencryptnginx_websites }}"
  register: create_csrs
  when: not item.use_snakeoil_certificate|default(False)
  become: true
