---
#- ansible.builtin.debug:
#      var: letsencryptnginx_websites

- import_tasks: apt.yml
- import_tasks: websites.yml
- import_tasks: nginx.yml
- import_tasks: csr.yml
- import_tasks: letsencrypt.yml
