---
- name: Install system packages
  apt:
    name:
      - apache2-utils
      - nginx
      - python3-passlib
    state: latest
    update_cache: yes
  become: true

- name: Create HTTP Basic Authentication accounts
  htpasswd:
    path: /etc/nginx/{{ item.0.domain }}.htpasswd
    name: "{{ item.1.username }}"
    password: "{{ item.1.password }}"
    owner: root
    group: www-data
    mode: 0640
  when: item.1 is defined
  with_subelements:
    - "{{ letsencryptnginx_websites }}"
    - http_basic_authentication.credentials
    - skip_missing: True
  become: true

- name: Create HTTP Basic Authentication accounts for aliases
  htpasswd:
    path: /etc/nginx/{{ item.0.password_filename }}
    name: "{{ item.1.username }}"
    password: "{{ item.1.password }}"
    owner: root
    group: www-data
    mode: 0640
  when: item.1 is defined
  with_subelements:
    - "{{ letsencryptnginx_websites | selectattr('aliases','defined') | map(attribute='aliases') | flatten | selectattr('http_basic_authentication','defined') | map(attribute='http_basic_authentication') | flatten }}"
    - credentials
    - skip_missing: True
  become: true

- name: Create letsencryptnginx_web_root_directory
  file:
    path: "{{ letsencryptnginx_web_root_directory }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 2775
  become: true

- name: Clone website repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ letsencryptnginx_web_root_directory }}/{{ item.domain }}"
    version: "{{ item.version|default('HEAD') }}"
  loop: "{{ letsencryptnginx_websites }}"
  register: git_clone
  when: item.repo is defined
  become: true

- name: Run website commands
  shell: "{{ item.item.command }}"
  args:
    chdir: "{{ letsencryptnginx_web_root_directory }}/{{ item.item.domain }}"
  loop: "{{ git_clone.results }}"
  when:
    - item.changed and 'command' in item.item
    - item is not skipped
  become: true

- name: Chown repo directrories
  file:
    path: "{{ letsencryptnginx_web_root_directory }}/{{ item.domain }}"
    owner: www-data
    group: www-data
  loop: "{{ letsencryptnginx_websites }}"
  when: item.repo is defined
  become: true

- name: Create website web_root directories
  file:
    path: "{{ letsencryptnginx_web_root_directory }}/{{ item.domain }}"
    owner: www-data
    group: www-data
    state: directory
  loop: "{{ letsencryptnginx_websites }}"
  when: item.repo is not defined and item.proxy_port is not defined
  become: true

- name: Delete sites-available and sites-enabled directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled
  become: true

- name: Create sites-enabled directory
  file:
    path: /etc/nginx/sites-enabled
    state: directory
  become: true

- name: Copy snippets
  copy:
    src: "{{ item }}"
    dest: /etc/nginx/snippets/
  loop:
    - common_site_configuration
    - proxy_params
  notify: restart nginx
  become: true

- name: Overwrite proxy_params
  copy:
    src: proxy_params
    dest: /etc/nginx/
  notify: restart nginx
  become: true

- name: Copy default site config
  copy:
    src: 00-default
    dest: /etc/nginx/sites-enabled
  notify: restart nginx
  become: true

- name: Check if HTTPS certificates are present
  stat:
    path: "{{ letsencryptnginx_crt_directory }}/{{ item.domain }}.crt"
  loop: "{{ letsencryptnginx_websites }}"
  register: certificates
  become: true

- name: Copy site configs
  template:
    src: site.j2
    dest: /etc/nginx/sites-enabled/{{ item.item.domain }}
  loop: "{{ certificates.results }}"
  notify: restart nginx
  become: true
